from typing import Any, list, Callable, Union


class ZFCond:
    ZFCondCrippled: int = ...
    ZFCondIntimidated: int = ...
    ZFCondPoisoned: int = ...
    ZFCondTracked: int = ...


class ZFStat:
    ZFStatAtt: int = ...
    ZFStatCrit: int = ...
    ZFStatDef: int = ...
    ZFStatRof: int = ...
    ZFStatSpeed: int = ...
    ZFStat_Count: int = ...


class ZFStatType:
    ZFStatTypeCond: int = ...
    ZFStatTypePerm: int = ...
    ZFStatTypeTemp: int = ...
    ZFStatTypeTempDuration: int = ...


TOTAL_ZFSTATS: Any = ...  # 5
TOTAL_ZFSTAT_TYPES: Any = ...  # 4
TOTAL_ZFCONDS: Any = ...  # 4
MAX_ITEMS: Any = ...  # 5